### ISSUE TITLE
Error in train.py line 572 and 588

### ISSUE THREAD

**Issue by sandruskyi** [BorealisAI/towards-better-sel-cls#2]
Hi! 
I think there is an error in train.py, evaluate method, line 572. 
The current code is: 
`
sr_scores, sr_correct = torch.stack(abortion_results[0]), torch.stack(abortion_results[1])
`

If I am correct, it needs to be: 
`
sr_scores, sr_correct = torch.stack(sr_results[0]), torch.stack(sr_results[1])
`

And in line 588: 
Current: 
`        
print('{:.0f},\t{:.2f},\t\t{:.3f}'.format(expected_coverage[idx], abortion_results[idx][0]*100., (1 - abortion_results[idx][1])*100))
`
Correct (?): 
`        
print('{:.0f},\t{:.2f},\t\t{:.3f}'.format(expected_coverage[idx], sr_results[idx][0] * 100., (1 - sr_results[idx][1]) * 100))`

I don´t know if these changes could affect your paper results.
Thanks, 
Sandra Gómez-Gálvez

**Comment by leofeng-ca** [comment]
Hi Sandra! 

Sorry for the late reply. I haven't checked the repo in a while. 

You're right regarding the typos. It won't affect the paper results since the model's training has not changed. The final results and analyses were performed using the trained models separately on a jupyter notebook. The code for console logging with SR was added later.

I've pushed an update fixing the evaluate script for console logging. Also, I just noticed that you made a pull request. If I had seen it earlier, I would've just merged that instead. Thank you for catching the issue!

**Comment by sandruskyi** [comment]
Hey @lfeng99 ! 
Don´t worry, we are always busy, thank you for fixing it :-)
Could be possible to have available that jupyter notebook? I am trying to replicate your results for my next paper, to compare and verify. 
I can contact you by email if you prefer. 
Thank you!
